### ISSUE TITLE
[Feature Request] Expose bagged error estimates in lolopy

### ISSUE THREAD

**Issue by zdelrosario** [CitrineInformatics/lolo#192]
Bagged estimates are available within [lolo](https://github.com/CitrineInformatics/lolo/blob/develop/src/main/scala/io/citrine/lolo/bags/Bagger.scala#L190), but from what I can tell are not exposed in lolopy. Request that such features be given a python interface.

**Comment by bfolie** [comment]
Uncertainty estimates are now available in lolopy using the `return_std` and `return_cov_matrix` arguments: https://github.com/CitrineInformatics/lolo/blob/main/python/lolopy/learners.py#L209
