### ISSUE TITLE
Extremely randomized trees

### ISSUE THREAD

**Issue by mrupp-citrine** [CitrineInformatics/lolo#214]
Implement extremely randomized trees in `lolo`.

In extremely randomized trees, split thresholds are drawn at random and the best split is selected. This usually reduces variance at the expense of increasing bias.

See

[ExtraTreesRegressor @ scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.ExtraTreesRegressor.html)

Pierre Geurts, Damien Ernst, Louis Wehenkel: Extremely randomized trees,
Machine Learning 63: 3--42, 2006. DOI [10.1007/s10994-006-6226-1](https://doi.org/10.1007/s10994-006-6226-1)

**Comment by gregor-robinson** [comment]
Implemented by https://github.com/CitrineInformatics/lolo/pull/220, so it's ready for roll-out in the next release.
