### ISSUE TITLE
Feature importances should factor in linear model weights for linear leaves

### ISSUE THREAD

**Issue by eantono** [CitrineInformatics/lolo#69]
Once standardization is in place, we should think about how to factor linear model weights into feature importances.

**Comment by maxhutch** [comment]
Agreed.  The tree importances are based on changes in impurity across a split.  In that vein, we could take the remaining impurity at the leaf and distribute it across the features in the leaf model weighted by their internal importance.  This would be _easy_ to implement.

Thoughts?  CC: @jling11 @sparadiso

**Comment by sparadiso** [comment]
That seems reasonable.
